spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?serverTimezone=UTC
    username: root
    password: 19990425
mybatis:
  type-aliases-package: com.demo.pojo
